### ISSUE TITLE
Rhvoice for android crash,when i try to export config file

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [RHVoice/RHVoice#633]
Hello everybody. When i in tts settings of rhvoice want to export a config file,rhvoice is crash with exception:

10-02 20:00:57.508 25217 25217 E AndroidRuntime: Process: com.github.olga_yakovleva.rhvoice.android, PID: 25217
10-02 20:00:57.508 25217 25217 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT typ=*/* (has extras) }
10-02 20:00:57.508 25217 25217 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1937)
10-02 20:00:57.508 25217 25217 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
10-02 20:00:57.508 25217 25217 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4522)
10-02 20:00:57.508 25217 25217 E AndroidRuntime: 	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
10-02 20:00:57.508 25217 25217 E AndroidRuntime: 	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:239)
10-02 20:00:57.508 25217 25217 E AndroidRuntime: 	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)
10-02 20:00:57.508 25217 25217 E AndroidRuntime: 	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
10-02 20:00:57.508 25217 25217 E AndroidRuntime: 	at androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)
10-02 20:00:57.508 25217 25217 E AndroidRuntime: 	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
10-02 20:00:57.508 25217 25217 E AndroidRuntime: 	at com.github.olga_yakovleva.rhvoice.android.SettingsFragment.onConfigFilePrefChange(SettingsFragment.java:238)
10-02 20:00:57.508 25217 25217 E AndroidRuntime: 	at com.github.olga_yakovleva.rhvoice.android.SettingsFragment.$r8$lambda$LpdLPAsjX0a97Agj4Sobexxo5qA(Unknown Source:0)
10-02 20:00:57.508 25217 25217 E AndroidRuntime: 	at com.github.olga_yakovleva.rhvoice.android.SettingsFragment$$ExternalSyntheticLambda2.onPreferenceChange(Unknown Source:2)

Yes,it restores,but if it possible,please,fix this issue. I have phone with modified firmware,and this phone haven't activity with this action. So,@Olga-Yakovleva,can you please,if this exception will be thrown,try export config file from internal memory,using path to file,as it should be according documentation. If you will not find config file here,pleas imput information,about failure of export config file,because we haven't need activity and in internal path %s you couldn't find this file. Thanks.

**Comment by alex19EP** [comment]
hmm. is it normal if rom isn't providing [DocumentsUI](https://source.android.com/docs/core/architecture/modular-system/documentsui)? I don't think so.

**Comment by AlexandrKozlovskiy** [comment]
@alex19EP It's phone,which develop special for blind. More details in telegram privately,if you want. In my opinion,it should be fixed for this situation.

**Comment by qkqsb** [comment]
Possibly related to https://github.com/RHVoice/RHVoice/issues/594

**Comment by beqabeqa473** [comment]
Please explain in details, what type of device you are using, so we could have understanding of issue.

**Comment by AlexandrKozlovskiy** [comment]
I have agm m7 device with firmware from slepsung company and file manager of this firmware not support system intent actions such as open_document,get_content,create_document etc.
